version: '3'
services:
    api:
        build: .
        ports:
            - "8000:8000"
        links:
            - mongo
    mongo:
        image: mongo:4.2
        ports:
            - "27017:27017"
        expose:
            - "27017-27019"